# Generated by Django 6.0.5 on 2026-05-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0002_esgrecord_normalized_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgrecord',
            name='occurred_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
